export const PsPalette = {
	BLACK: "#000000",
	DEEP_BLUE: "#2b335f",
	SLATE: "#7e2072",
	STEEL: "#19959c",
	MAUVE: "#8b4852",
	COBALT: "#395c98",
	PALE_BLUE: "#a9c1ff",
	WHITE: "#eeeeee",
	CRIMSON: "#d4186c",
	OCHRE: "#d38441",
	GOLD: "#e9c35b",
	GRAY: "#a3a3a3",
	SEAFOAM: "#70c6a9",
	PERIWINKLE: "#7696de",
	PINK: "#ff9798",
	PEACH: "#edc7b0",
} as const;

export const PsPaletteArray = [
	PsPalette.BLACK,
	PsPalette.DEEP_BLUE,
	PsPalette.SLATE,
	PsPalette.STEEL,
	PsPalette.MAUVE,
	PsPalette.COBALT,
	PsPalette.PALE_BLUE,
	PsPalette.WHITE,
	PsPalette.CRIMSON,
	PsPalette.OCHRE,
	PsPalette.GOLD,
	PsPalette.GRAY,
	PsPalette.SEAFOAM,
	PsPalette.PERIWINKLE,
	PsPalette.PINK,
	PsPalette.PEACH,
] as const;
